### ISSUE TITLE
Support linking `@link` tags

### ISSUE THREAD

**Issue by mbabker** [joomla/api.joomla.org#2]

**Comment by zero-24** [comment]
Do you already know what to do for that?

**Comment by mbabker** [comment]
Probably something similar to what we do for the `@see` tag (https://github.com/joomla/api.joomla.org/blob/master/class/details.method.html.twig#L22-L28) but I'll probably need to figure out what exactly the `tag` object is that's being processed to sort out how to parse it (for links with a description we'd only want the actual link to be linked and display the rest of the description as regular text).

**Comment by mbabker** [comment]
I think https://github.com/phpDocumentor/ReflectionDocBlock is the library holding the objects representing the various tags, so it's just matching that up with whatever phpDocumentor 2.9 is using and handling things as needed.

**Comment by zero-24** [comment]
I have just done a first PR for the first one but please review as i don't know how that twing thing works.

**Comment by mbabker** [comment]
As noted, not required, already works.
