### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by brianteeman** [joomla/api.joomla.org#37]
Since @bembelimen changed the deprecation dates etc with https://github.com/joomla/joomla-cms/pull/38657 the API docs need to be regenerated. 

I don't have the necessary permissions or I would have done it myself

**Comment by Hackwar** [comment]
I triggered the rebuild. Can you check if everything as you expect?

**Comment by brianteeman** [comment]
Thanks - shouldnt it be an automatic process?

**Comment by wilsonge** [comment]
It’s always been done manually as part of the release checklist. So that we always get the stable release docs

**Comment by Hackwar** [comment]
Not since at least 4.2...

**Comment by wilsonge** [comment]
Well then we need to update the release docs……
