### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by jameswadsworth** [joomla/api.joomla.org#41]
I noticed that since 01 Oct 2023 the site api.joomla.org is down. 

![Screenshot from 2023-10-02 19-21-46](https://github.com/joomla/api.joomla.org/assets/9198869/e39c2ace-7115-4d4d-81a2-ab07ba665afe)

I've checked with a 3rd party website https://isitdownorjust.me and it shows down as well. 

![Screenshot from 2023-10-02 19-23-09](https://github.com/joomla/api.joomla.org/assets/9198869/4b871c28-a3a5-4c6c-a526-bb5948d2a315)

**Comment by HLeithner** [comment]
Thanks for the report, we are aware of this issue and waiting of our hosting provider to solve the situation: https://www.rochen.com/docs/documentation/us-vsan-network-status/
