### ISSUE TITLE
Missing page (404)

### ISSUE THREAD

**Issue by alve89** [joomla/api.joomla.org#5]
Hey guys,

the following page is missing: https://api.joomla.org/cms-3/classes/JAuthenticationResponse.html

Now I'm asking how I can make it, that the function onUserAuthorisation() denies a users login. What does this method need to return?

**Comment by mbabker** [comment]
See https://api.joomla.org/cms-3/classes/Joomla.CMS.Authentication.AuthenticationResponse.html for the renamed class.

See https://github.com/joomla/joomla-websites/issues/1100 for outstanding redirect task.

> Now I'm asking how I can make it, that the function onUserAuthorisation() denies a users login. What does this method need to return?

I would suggest checking existing authentication plugins for that.  But in general the response object's status property should match one of the `STATUS_` constants in the [Authentication class](https://api.joomla.org/cms-3/classes/Joomla.CMS.Authentication.Authentication.html).  If you need further coding help please use the forums or mailing lists for that.
